<?php

namespace Doxy\Generator;

use Doxy\Model\Config;
use RuntimeException;

class NginxGenerator
{
    public function generate(Config $config)
    {
        $path = rtrim(getenv('DOXY_NGINX_OUTPUT_PATH'), '/');
        if (!$path) {
            $path = '/etc/nginx/sites-enabled';
        }
        if (!$path || !file_exists($path)) {
            throw new RuntimeException("DOXY_NGINX_OUTPUT_PATH not configured correctly: " . $path);
        }

        $loader = new \Twig_Loader_Filesystem(__DIR__ . '/../../templates');
        $twig = new \Twig_Environment($loader, []);

        $conf = '# Generated by doxy ' . date('Y-m-d H:i:s') . " - DO NOT EDIT MANUALLY\n";
        foreach ($config->getServers() as $server) {
            $conf .= '###### ' . $server->getName() . ' ######' . "\n";
            $data = [];
            $data['server'] = $server;
            $content = $twig->render('nginx-server.conf.twig', $data);
            $conf .= $content;
        }
        $filename = $path . '/doxy.conf';
        file_put_contents($filename, $conf);
    }
}
